# Generated by Django 2.2.6 on 2019-11-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0002_auto_20191021_2005'),
    ]

    operations = [
        migrations.RunSQL(
            sql = 'alter table tovar_tovar add column picture bytea ;',
            reverse_sql= 'alter table tovar_tovar drop column picture ;'
        ),
    ]
